#spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/builder_db}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:Naveen21()}
#spring.jpa.hibernate.ddl-auto=${SPRING_JPA_HIBERNATE_DDL_AUTO:update}
#spring.jpa.show-sql=true
#
#app.jwt.secret=${APP_JWT_SECRET:buildtrack-super-secret-key-that-is-at-least-256-bits-long-for-hmac-sha}
#app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}
#
#server.port=8080

spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect

spring.main.lazy-initialization=true
server.address=0.0.0.0

spring.datasource.hikari.initialization-fail-timeout=0
spring.datasource.hikari.validation-timeout=3000
spring.datasource.hikari.connection-timeout=10000

app.jwt.secret=${APP_JWT_SECRET:buildtrack-super-secret-key-that-is-at-least-256-bits-long-for-hmac-sha}
app.jwt.expiration=${APP_JWT_EXPIRATION:86400000}

server.port=${PORT:8080}
